config/routes.rb
Rails3Base::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

#  root :to => redirect{|p, req| "http://schandflecken.wordpress.com" }
   root :to => "landingpage#index"
#  match "/" => redirect{|p, req| "http://schandflecken.wordpress.com" }

  resources :subscriptions do
     member do
       get 'confirm'
       get 'unsubscribe'
     end
   end

  resources :incident_reports do
    member do
      IncidentReportsController::STATES.each do |state|
        get state
      end
    end
    
    collection do
      post :update_attribute_on_the_spot
    end

    resources :comments, :controller => 'incident_report_comments'
  end

  # static pages
  match "/agb" => "misc#agb"
  match "/faq" => "misc#faq"
  match "/contributors" => "misc#contributors"  

  # API access
  scope '/1' do
    resources :incident_reports, :controller => 'api/incident_reports'
  end
  
  # TODO only allow access to admins
  namespace :admin do
    resources :incident_reports
    resources :users
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :incident_report
  belongs_to :author, :class_name => 'User'
  
  validates_presence_of :body
  validates_length_of :body, :maximum => 255
end

app/views/comments/_comment.html.erb
<div class="left_column_content_incident">
	<div id="incident_comment_picture" class="left_column_content_incident_comment_description">
		<%= image_tag "user-02.jpg" %>
	</div>

	<div id="incident_comment_text" class="right_column_content_incident_comment_description">
		Name: <%= comment.author.full_name if comment.author %><br></br>
		<%= comment.body %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for(comment, :url => incident_report_comments_path(comment.incident_report), :remote => true) do |f| %>
	<fieldset>
		<div class="description">
			<%= f.text_area :body, :size => "31x3" %>
  		<%= f.submit "submit", :html => { :style => "margin-top:5px; margin-bottom:5px; margin-right:0px;"} %>
		</div>
	</fieldset>
<% end %>