config/routes.rb
Rails3Base::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

#  root :to => redirect{|p, req| "http://schandflecken.wordpress.com" }
   root :to => "landingpage#index"
#  match "/" => redirect{|p, req| "http://schandflecken.wordpress.com" }

  resources :subscriptions do
     member do
       get 'confirm'
       get 'unsubscribe'
     end
   end

  resources :incident_reports do
    member do
      IncidentReportsController::STATES.each do |state|
        get state
      end
    end
    
    collection do
      post :update_attribute_on_the_spot
    end

    resources :comments, :controller => 'incident_report_comments'
  end

  # static pages
  match "/agb" => "misc#agb"
  match "/faq" => "misc#faq"
  match "/contributors" => "misc#contributors"  

  # API access
  scope '/1' do
    resources :incident_reports, :controller => 'api/incident_reports'
  end
  
  # TODO only allow access to admins
  namespace :admin do
    resources :incident_reports
    resources :users
  end
end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController 
  def index
    @latest_incident_reports = IncidentReport.published.latest(3)
    @solved_incident_reports = IncidentReport.solved.latest(3)
  end
end

app/views/landingpage/_incident_block.html.erb
<li>
	<% if incident_block.image.nil? %>
		display some place-holder image
	<% else %>
		<%= link_to(image_tag(incident_block.image.image.url(:incident_block), :class => "incident_blockimg"),incident_report_path(incident_block), :html => { :border => 0 }) %>
	<% end %>
	
	<%= truncate(incident_block.description, :length => 50) %><br/>
	<small>
		Kommentare: <%= incident_block.comments.count %><br/>
		
		<div>
			<% if incident_block.dislikers.count == 0 %>
				<%= image_tag 'dislike-transparent.gif' %>
			<% else %>
				<%= image_tag 'dislike-full.gif' %> <%= incident_block.dislikers.count %>
			<% end %>

			<% if incident_block.no_problemers.count == 0 %>
				<%= image_tag 'no-problem-transparent.gif'%>
			<% else %>
				<%= image_tag 'no-problem-full.gif' %> <%= incident_block.no_problemers.count %>
			<% end %>

			<% if incident_block.resolvers.count == 0 %>
				<%= image_tag 'behoben-transparent.gif'%>
			<% else %>
				<%= image_tag 'behoben-full.gif' %> <%= incident_block.resolvers.count %>
			<% end %>
		</div>
	</small>
</li>
<!-- we should have a nice badge for the dislike counter (like the retweet count badge) -->

app/views/landingpage/index.html.erb
<% content_for :head do %>
    <script type="text/javascript"
      src="http://maps.google.com/maps?file=api&v=2&key=<%= configatron.gmapkeyv2 %>&sensor=false" >
    </script>
    <%= javascript_include_tag 'clustermap' %>
    <%= javascript_include_tag 'data' %>
    <%= javascript_include_tag 'markerclusterer' %>

<% end %>

<div id="landingpage">
	<%= image_tag("banner.png", :alt => configatron.app_name) %>
		<span class="title">In deiner Stadt</span>
		<div id="map" style="background: #fff; width:800px; height: 300px;"></div>


			<script type="text/javascript">
					$(document).ready(function(){
              async_clustermap("map", 45, 16, 4, "/1/incident_reports.json");
					});
			</script>
 
	<div id="main_content">
		<div class="col">
			<h2>Neue Schandflecken</h2>
			<% if @latest_incident_reports.nil? || @latest_incident_reports.empty? %>
				Keine Schandflecken vorhanden
			<% else %>
				<ul class="incidentlist">
					<%= render :partial => 'incident_block', :collection => @latest_incident_reports %>
				</ul>
			<% end %>
		</div>
		
		<div class="col">
			<h2>Behobene Schandflecken</h2>
			<% if @solved_incident_reports.nil? || @solved_incident_reports.empty? %>
				Noch keine Schandflecken behoben
			<% else %>
				<ul class="incidentlist">
					<%= render :partial => 'incident_block', :collection => @solved_incident_reports %>
				</ul>
			<% end %>
		</div>

		<div class="col">
			<h2>Wie kann ich mitmachen?</h2>
				Add Text here
		</div>	
	<div class="clear"></div>
	</div> <!--main_content-->
</div>