config/routes.rb
Rails3Base::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

#  root :to => redirect{|p, req| "http://schandflecken.wordpress.com" }
   root :to => "landingpage#index"
#  match "/" => redirect{|p, req| "http://schandflecken.wordpress.com" }

  resources :subscriptions do
     member do
       get 'confirm'
       get 'unsubscribe'
     end
   end

  resources :incident_reports do
    member do
      IncidentReportsController::STATES.each do |state|
        get state
      end
    end
    
    collection do
      post :update_attribute_on_the_spot
    end

    resources :comments, :controller => 'incident_report_comments'
  end

  # static pages
  match "/agb" => "misc#agb"
  match "/faq" => "misc#faq"
  match "/contributors" => "misc#contributors"  

  # API access
  scope '/1' do
    resources :incident_reports, :controller => 'api/incident_reports'
  end
  
  # TODO only allow access to admins
  namespace :admin do
    resources :incident_reports
    resources :users
  end
end

app/models/incident_report.rb
class IncidentReport < ActiveRecord::Base
  include AASM

  attr_accessor :facebook
  
  belongs_to :author, :class_name => 'User'
  has_one :image, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates_presence_of :author, :image
  validates_numericality_of :latitude, :allow_nil => true
  validates_numericality_of :longitude, :allow_nil => true
  validates_length_of :description, :maximum => 255
  
  after_create :deliver_new_incident_notification
  
  has_many :incident_reports_users, :dependent => :destroy
  has_many :dislikers, :class_name => 'User', :through => :incident_reports_users, :conditions => ["type = ?", "dislike"], :source => :user
  has_many :no_problemers, :class_name => 'User', :through => :incident_reports_users, :conditions => ["type = ?", "not_a_problem"], :source => :user
  has_many :resolvers, :class_name => 'User', :through => :incident_reports_users, :conditions => ["type = ?", "resolved"], :source => :user
  
  # use geometrical distance
  scope :incidents_within, lambda {
                |longitude, latitude, range_x, range_y, limit|
                  where("longitude between ? and ? and latitude between ? and ?",
                        longitude - range_x, longitude + range_x, latitude - range_y, latitude + range_y).limit(limit)
              }
              
  scope :solved, where("aasm_state = ?", 'solved')
  scope :published, where("aasm_state = ?", 'published')
  scope :latest, lambda { |count| order("created_at DESC").limit(count) }

  aasm_initial_state :published

  aasm_state :published
  aasm_state :not_a_problem
  aasm_state :solved

  aasm_event :solve do
    transitions :to => :solved, :from => [:published, :not_a_problem]
  end
  
  aasm_event :mark_as_not_a_problem do
    transitions :to => :not_a_problem, :from => [:published]
  end
  
  def next
    IncidentReport.where("created_at > ?", created_at).limit(1).order("created_at ASC").first
  end
  
  def previous
    IncidentReport.where("created_at < ?", created_at).limit(1).order("created_at DESC").first
  end
  
  def deliver_new_incident_notification
    Subscription.within(self.longitude, self.latitude).each do |subscription|
      SubscriptionMailer.new_incident(self, subscription).deliver
    end
  end
  
  def location_valid?
    latitude && longitude && latitude > 0.0 && longitude > 0.0
  end
  
  def user_name
    author.full_name if author
  end
  
  def user_name=(new_name)
    if self.author
      self.author.full_name = new_name
      self.athor.save
    else
      # TODO: we need user management..
      self.author = User.find_or_create_by_email("someemailaddress@somedomain.xxx")
      self.author.password = self.author.password_confirmation = "fubar again"
      self.author.full_name = new_name
      self.author.save!
    end
  end
  
  def upload_to_facebook(current_user, incident_url)
    if Rails.env == 'production'
      picture_url = "http://#{configatron.host}/#{self.image.image.url}"
    else
      picture_url = "http://schandflecken.files.wordpress.com/2010/12/2010-12-18-schandfleck-logo_wb_v1_940x198.png"
      incident_url = "http://schandfleck.in"
    end
    current_user.facebook.feed!(
      :message => 'Neuer Schandfleck in meiner Umgebung.',
      :picture => picture_url,
      :link => incident_url,
      :name => "Schandfleck at #{latitude} / #{longitude}",
      :description => description
    )
  end
  
end

app/controllers/admin/incident_reports_controller.rb
class Admin::IncidentReportsController < ApplicationController
  inherit_resources

  before_filter :authenticate_user!
  
  filter_resource_access

  protected

  def collection
    @admin_incident_reports ||= end_of_association_chain.paginate(:page => params[:page])
  end
end

app/controllers/api/incident_reports_controller.rb
require 'base64'

class Api::IncidentReportsController < ApplicationController
  
  respond_to :json

  DEFAULT_SEARCH_LIMIT = 10

  def create
    
    # unless params[:access_token]
    #   render :status => 401, :text => 'Access token required!'
    # end
    
    p = params[:incident_report] || {}
    
    # get oauth access token and perform authentication with facebook
    rg = RestGraph.new(:access_token => p[:access_token])
    begin
      fb_creds = rg.get('me')
    rescue
      render :status => 401, :text => 'Authentication failed'
      return
    end
    
    user = User.find_by_identity_for('facebook', fb_creds['id'], p[:access_token], nil)
    unless user
      # create user with facebook info from fb_creds
      user = User.new(:email => "#{fb_creds['id']}@facebook.com", :full_name => fb_creds['name'])
      user.skip_confirmation!

      user.identities.build(:provider => 'facebook', :uid => fb_creds['id'], :access_token => p[:access_token])
      user.save!
    end
        
    
    # accept either user or author
    #user = find_user(params[:user].blank? ? params[:author] : params[:user])

    # temporary create the incident report
    # TODO: move this into virtual model method?
    @incident_report = IncidentReport.new :latitude => p[:latitude],
                                          :longitude => p[:longitude],
                                          :description => p[:description],
                                          :author => user
    
    # store image data in a temporary file
    if p[:image].blank?
      render :status => 500, :text => "no image given"
      return
    elsif p[:image].is_a? ActionDispatch::Http::UploadedFile
      img = Image.new :image => p[:image],
                      :incident_report => @incident_report
      @incident_report.image = img
    else
      begin
        fp = File.open("/tmp/#{SecureRandom.hex(11)}.jpg", "wb+")
        size = fp.write Base64.decode64(p[:image])
        image = @incident_report.build_image :image => fp
        fp.close
      rescue
        render :status => 500, :text => "invalid image"
        return
      end
    end

    respond_to do |format|
      format.json do
        if @incident_report.save
          render :status => 200, :json => @incident_report.id
        else
          render :status => 500, :json => @incident_report.errors.full_messages.join(",").to_json
        end
      end
    end
  end

  def index
    # allow searches to be geographically scoped
    params[:limit] ||= DEFAULT_SEARCH_LIMIT
    
    if params.include?(:longitude) && params.include?(:latitude) && params.include?(:range_x) && params.include?(:range_y)
      @incident_reports ||= IncidentReport.incidents_within(params[:longitude].to_f,
                                                            params[:latitude].to_f,
                                                            params[:range_x].to_i,
                                                            params[:range_y].to_i,
                                                            params[:limit].to_i).includes(:image).includes(:author)
    else
      @incident_reports ||= IncidentReport.all
    end
    
    respond_to do |format|
      format.json do
        # prepare result statement
        render :json => @incident_reports.map {|ir| { :latitude => ir.latitude,
                                                      :longitude => ir.longitude,
                                                      :description => ir.description,
                                                      :user => ir.author ? ir.author.full_name : "anonymous",
                                                      :image => ir.image ? "http://#{configatron.host}#{ir.image.image.url}" : "none" }
        }
      end
    end
  end

  private

  # create user (currently shortcut)
  def find_user(username)
    user = User.find_or_create_by_full_name(params[:user])
    user.password = user.password_confirmation = params[:user]
    user
  end
end

app/controllers/incident_reports_controller.rb
require 'base64'

class IncidentReportsController < ApplicationController
  
  can_edit_on_the_spot
  
  before_filter :authenticate_user!, :except => [:index, :show, :feed]
#  filter_resource_access
  filter_access_to :all
  
  DEFAULT_SEARCH_LIMIT = 10
  STATES = ["dislike", "not_a_problem", "resolve"]
  
  STATES.each do |state|
    send :define_method, state do
      @ir = IncidentReport.find(params[:id])
      tmp = IncidentReportsUser.find_or_create_by_incident_report_id_and_user_id(@ir.id, @current_user.id)
      tmp.type = state == "resolve" ? "resolved" : state
      tmp.save!

      respond_to do |format|
        format.html { redirect_to incident_report_path(@ir.id) }
        format.js
      end
    end
  end

  def create
    # accept either user or author
    user = find_user(params[:user].blank? ? params[:author] : params[:user])

    # temporary create the incident report
    # TODO: move this into virtual model method?
    p = params[:incident_report] || {}
    @incident_report = IncidentReport.new( :author => @current_user )
    
    # store image data in a temporary file
    if p[:image].blank?
      render :status => 500, :text => "no image given"
      return
    elsif p[:image].is_a? ActionDispatch::Http::UploadedFile      
      img = Image.new :image => p[:image],
                      :content_type => p[:image].content_type,
                      :incident_report => @incident_report
      @incident_report.image = img
    else
      begin
        fp = File.open("/tmp/#{SecureRandom.hex(11)}.jpg", "wb+")
        size = fp.write Base64.decode64(p[:image])
        image = @incident_report.build_image :image => fp,
                                             :content_type => "image/jpeg"
        fp.close
      rescue
        render :status => 500, :text => "invalid image"
        return
      end
    end

    respond_to do |format|
      format.html do
        if @incident_report.save!
          redirect_to [:edit, @incident_report]
        else
          render :action => 'new'
        end
      end
    end
  end

  def show
    @incident_report ||= IncidentReport.find(params[:id])
    
    respond_to do |format|
      format.html
      format.atom { render :layout => false }
      format.rss { redirect_to incident_reports_path(:format => :atom), :status => :moved_permanently }
    end
  end

  def new
    @incident_report ||= IncidentReport.new
  end

  def update
    @incident_report = IncidentReport.find(params[:id])
    if @incident_report.update_attributes(params[:incident_report])
      
      incident_url = incident_report_url(@incident_report)
      
      if params[:incident_report][:facebook] == "1"
        @incident_report.upload_to_facebook(current_user, incident_url)
      end
      
      flash[:notice] = "Successfully updated incident report."
      redirect_to @incident_report
    else
      render :action => 'edit'
    end
  end


  def index
    # allow searches to be geographically scoped
    
    params[:limit] ||= DEFAULT_SEARCH_LIMIT
    
    if params.include?(:longitude) && params.include?(:latitude) && params.include?(:range_x) && params.include?(:range_y)
      @incident_reports ||= IncidentReport.incidents_within(params[:longitude].to_f,
                                                            params[:latitude].to_f,
                                                            params[:range_x].to_i,
                                                            params[:range_y].to_i,
                                                            params[:limit].to_i)
    else
      @incident_reports ||= IncidentReport.all
    end
    
    respond_to do |format|
      format.html
      format.atom { render :layout => false }
      format.rss { redirect_to incident_reports_path(:format => :atom), :status => :moved_permanently }
    end
  end

  def edit
    @incident_report ||= IncidentReport.find(params[:id])
  end

  protected

  # create user (currently shortcut)
  def find_user(username)
    user = User.find_or_create_by_full_name(params[:user])
    user.password = user.password_confirmation = params[:user]

    user
  end
end

app/helpers/incident_report_helper.rb
module IncidentReportHelper
  def prepare_markers(incident_reports)
    result  = "["
    incident_reports.each do |report|
      
      if incident_reports.first != report
        result += ", "
      end
      
      if !report.latitude.nil? && !report.longitude.nil?
        result += "{ 'lat':#{report.latitude}, 'long':#{report.longitude}, 'description':'#{report.description}'}"
      end
    end
    
    result += "]"
  end
end

app/views/incident_reports/_form.html.erb
<%= semantic_form_for(@incident_report, :html => { :multipart => true }) do |form| %>
  <%= form.inputs do %>
    <%= form.input :description %>
    <%= form.input :latitude %>
    <%= form.input :longitude %>
	<%= form.input :user_name %>
	<%= form.input :image, :as => :file %>
  <% end %>

  <%= form.buttons %>
<% end %>

app/views/incident_reports/_likes.html.erb
<!-- TODO switch between -full and -transparent image -->
<%= image_tag "dislike-full.gif" %>Stört das auch
<% if incident.dislikers.count > 0 %>
	(<%= incident.dislikers.count %>)
<% end %>
<br></br>

<%= image_tag "no-problem-full.gif" %>Ist kein Schandfleck
<% if incident.no_problemers.count > 0 %>
	(<%= incident.no_problemers.count %>)
<% end %>
<br></br>

<%= image_tag "behoben-transparent.gif" %>Schandfleck behoben
<% if incident.resolvers.count > 0 %>
	(<%= incident.resolvers.count %>)
<% end %>

app/views/incident_reports/dislike.js.erb
$('#incident_evaluation').html("<%= escape_javascript(render :partial => 'incident_reports/likes', :locals => {:incident => @ir}) %>");

app/views/incident_reports/edit.html.erb
<%= image_tag("banner.png", :alt => configatron.app_name) %>


<% content_for :head do %>
    <%= javascript_include_tag 'gmap' %>
    <script type="text/javascript"
          src="http://maps.google.com/maps/api/js?sensor=false">
    </script>
<% end %>

<p id="notice"><%= notice %></p>

<div id="incident_container" class="grid_12 ">
	<div class="left" class="grid_8 alpha">
		<div class="image">
			<%= image_tag(@incident_report.image.image.url, :size => "450x450") unless @incident_report.image.nil? %>
		</div>
		<!-- image -->
    	<div id="description">
        	<div class="avatar"></div><!--avatar-->
       		<p><%= @incident_report.description %></p>
		</div><!--description-->
        
			<div class="buttons">

<%= form_for(@incident_report, :html => { :multipart => true }) do |form| %>
  <%= form.inputs do %>
    <%= form.input :latitude, :as => :hidden  %>
    <%= form.input :longitude, :as => :hidden  %>
    <%= form.input :facebook, :as => :boolean, :label => "Post to Facebook" %>
    <%= form.input :description, :as => :text %>
  <% end %>

  <%= form.buttons %> or <%= link_to 'cancel', @current_object %>
<% end %>


        </div><!--buttons-->
        
	</div><!--left-->

	<div id="right" class="grid_4  omega">    
				<div id="map" style="background: #ccc; width:300px; height: 300px;"></div>
        <% if @incident_report.location_valid? %>
				<script type="text/javascript">
					$(document).ready(function(){
			    		dynamic_gmap_with_marker("map", <%= @incident_report.latitude %>, <%= @incident_report.longitude%>, "<%= escape_javascript(@incident_report.description) %>");
					});
				</script>
        <% else %>
				<script type="text/javascript">
					$(document).ready(function(){
              dynamic_gmap_with_marker("map", 46.62794, 14.30899, "");
					});
				</script>
			  <% end %>
        <form id="mapsearchform">
          <input id="address" /> 
          <input type=submit /> 
        </form>
				<script type="text/javascript">
					$(document).ready(function(){
            $('#mapsearchform').submit(function(){
              update_map_by_address($('#address').val());
              return false;
            })

            addMarkerChangedListener('incident_report_latitude', 'incident_report_longitude');
          });
				</script>
        
	</div><!--right-->
</div><!--container-->

app/views/incident_reports/index.html.erb
<% content_for :head do %>
	<%= auto_discovery_link_tag :atom, incident_reports_url(:atom) %>
	<%= auto_discovery_link_tag :rss, incident_reports_url(:rss) %>
	
	<%= javascript_include_tag 'gmap' %>
	<script type="text/javascript"
	        src="http://maps.google.com/maps/api/js?sensor=false">
	</script>
<% end %>

<div id="map" style="background: #ccc; width:929px; height: 600px;"></div>
<script type="text/javascript">
    a = <%= prepare_markers(@incident_reports); %>
		$(document).ready(function(){
	     static_gmap_with_markers("map", 46.62794, 14.30899, a);
		});
</script>

app/views/incident_reports/new.html.erb
<%= image_tag("banner.png", :alt => configatron.app_name) %>


<%= form_for(@incident_report, :html => { :multipart => true }) do |form| %>
	<%= form.text_field :image, :as => :file %>
  <%= form.submit %>
<% end %>

app/views/incident_reports/not_a_problem.js.erb
$('#incident_evaluation').html("<%= escape_javascript(render :partial => 'incident_reports/likes', :locals => {:incident => @ir}) %>");

app/views/incident_reports/resolve.js.erb
$('#incident_evaluation').html("<%= escape_javascript(render :partial => 'incident_reports/likes', :locals => {:incident => @ir}) %>");

app/views/incident_reports/show.html.erb
<%= image_tag("banner.png", :alt => configatron.app_name) %>
<% content_for :head do %>
    <%= javascript_include_tag 'gmap' %>
    <script type="text/javascript"
          src="http://maps.google.com/maps/api/js?sensor=false">
    </script>

		<% content_for :head do %>
			<%= auto_discovery_link_tag :atom, incident_report_url(@incident_report, :atom) %>
			<%= auto_discovery_link_tag :rss, incident_report_url(@incident_report, :rss) %>
			<%= javascript_include_tag :on_the_spot %>
		<% end %>
<% end %>

<p id="notice"><%= notice %></p>

<div class="left_column_content">

	<div id="incident_menu_left" class="left_column_content_incident">&lt;&nbsp;<%= link_to "voriger Eintrag", @incident_report.previous %></div>
	<div id="incident_menu_right" class="right_column_content_incident"><%= link_to "nächster Eintrag", @incident_report.next %>&nbsp;&gt</div>

	<div id="incident_picture" class="left_column_content_incident">
		<%= image_tag(@incident_report.image.image.url(:profile)) unless @incident_report.image.nil? %>
	</div>	
	
	<div id="incident_map" class="right_column_content_incident">
		<div id="map" style="background: #ccc; width:215px; height: 200px;"></div>
		</br>
		Datum: <%=l @incident_report.created_at.to_date %>
	</div>
	
	<% if @incident_report.location_valid? %>
		<script type="text/javascript">
				$(document).ready(function(){
		      static_gmap_with_marker("map", <%= @incident_report.latitude %>, <%= @incident_report.longitude%>, "<%= escape_javascript(@incident_report.description) %>");
				});
		</script>
  <% end %>
  
	<div style="clear:both"></div>

	<div id="incident_description" class="left_column_content_incident">
		<div id="incident_description_picture" class="left_column_content_incident_description">
			<%= image_tag "user-01.jpg "%>
		</div>
		
		<div id="incident_description_text" class="right_column_content_incident_description">
			Name:<br></br>
			<%= @incident_report.description %>
		</div>
	</div>
	
	<div id="incident_evaluation" class="right_column_content_incident">
		<%= render :partial => 'incident_reports/likes', :locals => { :incident => @incident_report } %>
	</div>
	
	<div style="clear:both"></div>
	
	<% if current_user %>
		<div id="incident_evaluation_button" class="left_column_content_incident_evaluation">
			<%= link_to image_tag('button-dislike-01.gif'), dislike_incident_report_path, :remote => true %>
  		<%= link_to image_tag('button-behoben-01.gif'), resolve_incident_report_path, :remote => true %>
  		<%= link_to image_tag('button-no-problem-01.gif'), not_a_problem_incident_report_path, :remote => true %>
		</div>
	<% end %>

<script src="http://connect.facebook.net/de_DE/all.js#xfbml=1"></script><fb:like href="http://schandfleck.in" show_faces="true" width="450" font="arial"></fb:like>

	<div style="clear:both"></div>

	<hr></hr>

	Kommentare:<br></br>
	<br></br>

	<div id="incident_comments">
		<%= render @incident_report.comments %>
	</div>


	<% @comment = @incident_report.comments.build %>
	<div id="incident_comments" class="left_column_content_incident_comment_own">
		<div id="incident_comment_own_empty" class="left_column_content_incident_comment_own_description">
		</div>
		<div id="incident_comment_own_text" class="right_column_content_incident_comment_own_description">
			<%= render :partial => 'comments/form', :locals => {:comment => @comment} %>
    </div>
	</div>
</div>

<div class="right_column_content_incident">
	WEITERE SCHANDFLECKEN
</div>

<div style="clear:both"></div>