config/routes.rb
Rails3Base::Application.routes.draw do
  devise_for :users,
      :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  as :user do
    get 'login', :to => 'devise/sessions#new', :as => 'new_user_session'
    get 'logout', :to => 'devise/sessions#destroy', :as => 'destroy_user_session'
    get 'signup', :to => 'devise/registrations#new', :as => 'new_user_registration'
  end

#  root :to => redirect{|p, req| "http://schandflecken.wordpress.com" }
   root :to => "landingpage#index"
#  match "/" => redirect{|p, req| "http://schandflecken.wordpress.com" }

  resources :subscriptions do
     member do
       get 'confirm'
       get 'unsubscribe'
     end
   end

  resources :incident_reports do
    member do
      IncidentReportsController::STATES.each do |state|
        get state
      end
    end
    
    collection do
      post :update_attribute_on_the_spot
    end

    resources :comments, :controller => 'incident_report_comments'
  end

  # static pages
  match "/agb" => "misc#agb"
  match "/faq" => "misc#faq"
  match "/contributors" => "misc#contributors"  

  # API access
  scope '/1' do
    resources :incident_reports, :controller => 'api/incident_reports'
  end
  
  # TODO only allow access to admins
  namespace :admin do
    resources :incident_reports
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  include User::OmniAuthExtension

  attr_accessible :full_name, :email, :password, :password_confirmation
  validates :full_name, :presence => true

  def full_name_with_email
    "#{self[:full_name]} (#{email})"
  end

  has_many :incident_reports, :dependent => :destroy, :foreign_key => :author_id
  has_many :comments, :dependent => :destroy, :foreign_key => :author_id
  has_many :incident_reports_users, :dependent => :destroy
  
  def role_symbols
    admin? ? [:admin] : [:user]
  end
  
  
  def facebook
    @fb_user ||= FbGraph::User.me(self.identities.find_by_provider('facebook').access_token)
  end
  
end

app/models/user/omni_auth_extension.rb
module User::OmniAuthExtension
  extend ActiveSupport::Concern

  included do
    has_many :identities, :class_name => 'UserIdentity', :dependent => :destroy
    devise :omniauthable
  end

  module ClassMethods
    # Find user by omniauth uid for specified provider
    # Or create new identity if user given
    #
    def find_by_identity_for(provider, uid, access_token, current_user)
      identity = UserIdentity.find_by_provider_and_uid(provider, uid)
      # check if we have an access token
      identity.update_attributes(:access_token => access_token) if identity.access_token.nil?
      return identity.user if identity

      if current_user
        current_user.identities.create!(:provider => provider, :uid => uid, :access_token => access_token)
        return current_user
      end

      nil
    end

    # Used by devise for initializing new User, received both params and session.
    # Builds aomniauth identity and fills user fields if omniauth data presents in the session
    #
    def new_with_session(params, session)
      super.tap do |user|
        if data = session['devise.omniauth_data']
          user.email = data['extra']['user_hash']['email'] if user.email.blank? && data['extra']['user_hash']['email'].present?
          user.full_name = data['extra']['user_hash']['name'] if user.full_name.blank? && data['extra']['user_hash']['name'].present?
          user.password = Devise.friendly_token[0,20]
          user.skip_confirmation!
          user.save


          user.identities.build(
              :provider => data['provider'],
              :uid => data['uid'],
              :access_token => data['credentials']['token'])
        end
      end
    end
  end

  module InstanceMethods
    def password_required?
      (identities.empty? || !password.blank? || !password_confirmation.blank?) && super
    end

    def valid_password?(password)
      return super if password_stored?
      true
    end

    def password_stored?
      encrypted_password_was.present?
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  inherit_resources
  
  before_filter :authenticate_user!
  
  filter_resource_access

  protected
  
  def resource_class
    User
  end

  def collection
    @admin_users ||= end_of_association_chain.paginate(:page => params[:page])
  end
  
  def resource
    if params[:id].blank?
      @admin_user ||= User.new
    else
      @admin_user ||= User.find(params[:id])
    end
  end
end

app/views/admin/users/_form.html.erb
<%= semantic_form_for resource, :url => resource.new_record? ? admin_users_path : admin_user_path(resource) do |form| %>
  <%= form.inputs do %>
    <%= form.input :full_name %>
    <%= form.input :email %>
    <%= form.input :password %>
    <%= form.input :password_confirmation %>
  <% end %>

  <%= form.buttons %> or <%= link_to 'cancel', :back %>
<% end %>

app/views/admin/users/edit.html.erb
<% title 'Editing admin_user' %>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<% title 'Listing admin_users' %>

<% unless @admin_users.blank? %>
  <%= table_for(@admin_users) do |t| %>
	<%= t.data :email, :full_name, :actions => :all, :action_prefix=>'admin' %>
  <% end %>
  <%= will_paginate(@admin_users) %>
<% else %>
  <p>Now it's time to create some data here. To create new entry, please use the button below.</p>
  <br /><br />
<% end %>

<br />

<p>
  <%= link_to 'New User', new_admin_user_path, :class => 'button' %>
</p>

app/views/admin/users/new.html.erb
<% title 'Create new admin_user' %>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @admin_user.full_name %>
</p>

<p>
  <b>Email:</b>
  <%= @admin_user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @admin_user.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @admin_user.password_confirmation %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>